stages:
  - deploy
deploy:
  stage: deploy
  script:
    - echo $deploy_ip
    - echo $CI_COMMIT_SHA
    - echo $branch_name
    - echo ${#branch_name}
    - echo `pwd`
    - command=`if [ ${#branch_name} == 0 ];then branch_name='devp';else echo $branch_name;fi`
    - SHA=`git log remotes/origin/$branch_name -1 --pretty=format:"%h"`
    - echo $SHA
    - echo $branch_name
    - bash /home/gitlab-runner/cedar_deploy.sh $deploy_ip $SHA $branch_name
  only:
    - schedules
  tags:
    - deploy