stages:
  - deploy
deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - ls
    - rm -rf tmp || true
    - mkdir tmp
    - cp -rf dist tmp/cedar
    - docker cp tmp/cedar cedar:/app/cedar
    - rm -rf tmp
    - ls
  only:
    - master
  tags:
    - deploy