stages:
  - deploy
deploy:
  stage: deploy
  script:
    ssh root@182.92.218.230 "cd /etc/cedar/conf; pwd; sh cedar_deploy.sh"
    ssh root@39.105.123.128 "cd /etc/cedar/conf; pwd; sh cedar_deploy.sh"
  only:
    - master
  tags:
    - deploy