stages:
  - deploy
deploy:
  stage: deploy
  script:
    - echo $deploy_ip
    - echo $CI_COMMIT_SHA
    - echo $branch_name
    - echo `pwd`
    - bash /home/gitlab-runner/cedar_deploy.sh $deploy_ip $CI_COMMIT_SHA $branch_name
  only:
    - schedules
  tags:
    - deploy