stages:
  - build
  - push
#    - deploy

variables:
  docker_storage_username: 17625646261
  docker_storage_passwd: aaa626181
  docker_storage_url: registry.cn-beijing.aliyuncs.com
  module_name: cedar
  ssh_remote_ip: 10.80.6.101
  ssh_remote_username: root

before_script:
  - docker_images_tag=`git log -1 --pretty=format:"%h"`
  - DATE=`date +%Y%m%d`

build:
  stage: build
  script:
    - echo $deploy_ip
    - echo $branch_name
    - echo $CI_COMMIT_SHA
    - echo `pwd`
    - bash /home/gitlab-runner/cedar_deploy.sh $deploy_ip $CI_COMMIT_SHA $branch_name
  only:
    - 15num-k8s-develop
  tags:
    - push

push:
  stage: push
  script:
    - pwd
    - w
    - docker login -u $docker_storage_username -p $docker_storage_passwd $docker_storage_url
    - docker tag $docker_storage_url/wavecut/$module_name:$DATE-$docker_images_tag $docker_storage_url/wavecut/$module_name:latest
    - docker push $docker_storage_url/wavecut/$module_name:$DATE-$docker_images_tag
    - docker push $docker_storage_url/wavecut/$module_name:latest
#    - ssh $ssh_remote_username@$ssh_remote_ip "pwd ; bash deploy.sh $module_name $docker_storage_url/wavecut/$module_name:$DATE-$docker_images_tag"
  only:
    - 15num-k8s-develop
  tags:
    - push



#stages:
#  - deploy
#deploy:
#  stage: deploy
#  script:
#    - npm install
#    - cp /etc/cedar/conf/ip.js public/ip.js
#    - npm run build
#    - ls
#    - rm -rf tmp || true
#    - mkdir tmp
#    - cp -rf dist tmp/cedar
#    - docker exec cedar rm -rf /app/cedar || true
#    - docker cp tmp/cedar cedar:/app
#    - rm -rf tmp
#    - ls
#    - docker restart cedar
#  only:
#    - devp
#  tags:
#    - deploy

