stages:
  - deploy
deploy:
  stage: deploy
  script:
    - npm install
    - cp /etc/cedar/conf/ip.js public/ip.js
    - vue-cli-service build --mode development
    - ls
    - rm -rf tmp || true
    - mkdir tmp
    - cp -rf dist tmp/cedar
    - docker exec cedar rm -rf /app/cedar || true
    - docker cp tmp/cedar cedar:/app
    - rm -rf tmp
    - ls
    - docker restart cedar
  only:
    - master
  tags:
    - deploy